### ISSUE TITLE
Using @each for emoticons

### ISSUE THREAD

**Issue by dimaursu** [jsxc/jsxc#138]
```css
.jsxc_emoticon {
    display: inline-block;
    width: 19px;
    height: 19px;
    background-size: 19px 19px !important;
    border: 0;
}
$emoticons: angel, angry, smile, grin, sad, wink, tonguesmile, surpised, kiss,
            sunglassess, crysad, doubt, zip, thumbsup, thumbsdown, beer, devil,
            kissing, rose, music, love, tired;

@each $emoticon in $emoticons {
    .jsxc_#{$emoticon} { background: image-url('emotions/#{$emoticon}.png'); }
}
```
This should replace the whole emoticons.scss file, and as you can see is way shorter. 
I would have submitted a PR, but unfortunately I already run `node 0.12`, and this means I had to switch to `grunt-contrib-sass` (the more feature complete compiler, but a bit slower - because it's written in ruby), just to test my changes. I didn't wanted to pollute the PR with other changes.
