### ISSUE TITLE
Transfer files between Pidgin and JSXC does not work

### ISSUE THREAD

**Issue by DwijadasDey** [jsxc/jsxc#604]
I am facing an issue of transferring files from pidgin to JSXC. While file transfers between pidgin to pidgin and JSXC to pidgin works fine. The file transfers between later used mod_http_upload: configuration in ejabberd configuration file that looks like below.

```
  mod_http_upload:
    docroot: "@HOME@/upload"
    put_url: "https://chat.demohost.com:5443/upload"
    get_url: "https:/chat.demohost.com:5443/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
      "Access-Control-Allow-Headers": "Content-Type"
  mod_http_upload_quota:
    max_days: 30
``` 
There is no issue of transferring files between JSXC to JSXC and JSXC to Pidgin as it taken care of by the above configuration.

To transfer files between two pidgin users , I have used mod_proxy65 configuration in ejabberd.yml that looks like below.

```
  mod_proxy65:
    host: "proxy.demohost.com"
    hostname: "proxy.demohost.local"
    name: "File proxy in demohost.com "
    port: 7777
    max_connections: 5
    access: trusted
    shaper: mod_proxy
```
 
Tried with following pidgin configurations->

```
Connect Port: 5222
Connect Server: chat.demohost.com
File transfer Proxies: proxy.demohost.com
BOSH URL: https://chat.demohost.com/http-bind/
```

When a user(through pidgin) tries to send a file to another user who is logged in JSCX. The error message says->
 File Send Failed
 Unable to send file to user@chat.demohost.com/example, user does not support file transfers

In the Pidgin message box->
(10:51:54 PM) Offering to send file.txt to dey@chat.demohost.com
(10:51:54 PM) You cancelled the transfer of file.txt

Is that a issue of JSXC/Pidgin or shall i need to configure something more in ejabberd configuration file ?
